"""empty message

Revision ID: 15d67b56c10a
Revises: 5b5dd7d7de51
Create Date: 2018-07-11 11:24:11.433577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15d67b56c10a"
down_revision = "5b5dd7d7de51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("html_url", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "html_url")
    # ### end Alembic commands ###
